[versions]
coreKtx = "1.13.1"
appcompat = "1.7.0"
lifecycleKtxVersion = "2.8.3"
kotlinReflect = "2.0.0"
lifecycleLivedataKtx = "2.8.3"
lifecycleViewmodelSavedstate = "2.8.3"
material = "1.12.0"
constraintLayout = "2.1.4"
lifecycleKtx = "2.8.3"
rxjava = "3.1.2"
rxandroid = "3.0.0"
rxkotlin = "3.0.1"
junit = "4.13.2"
androidxJunit = "1.2.1"
espressoCore = "3.6.1"
androidUtilities = "2.0.2"
androidBinding = "1.1.3"
androidViewex = "1.0.7"

[libraries]
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
lifecycleLiveDataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }
lifecycleViewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleKtx" }
lifecycleViewModelSavedState = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleKtx" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxkotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rxkotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
android-utilities = { module = "com.github.toyota-m2k:android-utilities", version.ref = "androidUtilities" }
android-binding = { module = "com.github.toyota-m2k:android-binding", version.ref = "androidBinding" }
android-viewex = { module = "com.github.toyota-m2k:android-viewex", version.ref = "androidViewex" }

[bundles]
androidTestImplementation = ["androidxJunit", "espressoCore"]